FROM debian:wheezy

MAINTAINER Manala <contact@manala.io>

WORKDIR /tmp

# Apt
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
        unzip \
        wget ca-certificates less \
        make

COPY scripts scripts

RUN bash scripts/ansible.sh \
    && bash scripts/ansible-lint.sh \
    && bash scripts/goss.sh

# Clean
RUN rm -rf * /var/lib/apt/lists/*

WORKDIR /srv
