FROM debian:wheezy

MAINTAINER Manala <contact@manala.io>

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /tmp

COPY scripts scripts

RUN bash scripts/apt.sh \
    && bash scripts/ansible.sh \
    && bash scripts/ansible-lint.sh \
    && bash scripts/goss.sh

RUN apt-get -y --no-install-recommends install \
    unzip \
    make

RUN bash scripts/clean.sh

WORKDIR /srv
